// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HYTwrJ9kJMClnN3W-vb0w2gUNoYVncQ',
    appId: '1:502210830112:web:757af7ed58278bd4178145',
    messagingSenderId: '502210830112',
    projectId: 'spotify-plus-c5e93',
    authDomain: 'spotify-plus-c5e93.firebaseapp.com',
    storageBucket: 'spotify-plus-c5e93.appspot.com',
    measurementId: 'G-1GWSV7C5Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAQbh92tWmpTBaaFSS2phYKijuf5xWa4s',
    appId: '1:502210830112:android:54e0b92de50baffe178145',
    messagingSenderId: '502210830112',
    projectId: 'spotify-plus-c5e93',
    storageBucket: 'spotify-plus-c5e93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhar7Cp4HvTfymiI2EBRIKz2rduYCYTnc',
    appId: '1:502210830112:ios:a4775385e1fcbf12178145',
    messagingSenderId: '502210830112',
    projectId: 'spotify-plus-c5e93',
    storageBucket: 'spotify-plus-c5e93.appspot.com',
    iosClientId: '502210830112-f2eoe47fb8kk6cibgkmo8p83lf0q3gka.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhar7Cp4HvTfymiI2EBRIKz2rduYCYTnc',
    appId: '1:502210830112:ios:a4775385e1fcbf12178145',
    messagingSenderId: '502210830112',
    projectId: 'spotify-plus-c5e93',
    storageBucket: 'spotify-plus-c5e93.appspot.com',
    iosClientId: '502210830112-f2eoe47fb8kk6cibgkmo8p83lf0q3gka.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyApp',
  );
}
